version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: xeno_fde
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - xeno-network

  backend:
    build: ./backend
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgresql://postgres:password@postgres:5432/xeno_fde
      JWT_SECRET: ${JWT_SECRET}
      NODE_ENV: production
    depends_on:
      - postgres
    command: sh -c "npx prisma migrate deploy && npm start"
    networks:
      - xeno-network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_API_URL: http://localhost:3001/api
    depends_on:
      - backend
    networks:
      - xeno-network

volumes:
  postgres_data:

networks:
  xeno-network:
    driver: bridge