@baseUrl = https://xeno-backend-u3yb.onrender.com
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJjbWZpaHMyM2swMDAwNGRhNW9lbW5ycmc4IiwiaWF0IjoxNzU3NzgxNjE2LCJleHAiOjE3NTgzODY0MTZ9.K0-jc2lcJv_SpU3FRuqOkXuwYxYhSHFAIch1ViHLdTE
@tenantId = cmfiht9ev00024da5r8lzv0bs
@email = {{email}}
@password = {{pasword}}

@shopifyDomain = shoplytics-demo-store.myshopify.com
@shopifyToken = {{shopify_token}}

### Health Check
GET {{baseUrl}}/health

### Register
POST {{baseUrl}}/api/auth/register
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Login
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{email}}",
  "password": "{{password}}"
}

### Create Tenant
POST {{baseUrl}}/api/tenant
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "name": "shoplytics-demo-store", 
  "shopifyDomain": "{{shopifyDomain}}",
  "shopifyToken": "{{shopifyToken}}"
}

### Get Tenants
GET {{baseUrl}}/api/tenant
Authorization: Bearer {{token}}

### Shopify Sync
POST {{baseUrl}}/api/shopify/sync
Authorization: Bearer {{token}}
x-tenant-id: {{tenantId}}

### Dashboard Stats
GET {{baseUrl}}/api/insights/dashboard?startDate=2023-01-01&endDate=2023-12-31
Authorization: Bearer {{token}}
x-tenant-id: {{tenantId}}

### Abandoned Carts
GET {{baseUrl}}/api/insights/abandoned-carts?startDate=2023-01-01&endDate=2023-12-31
Authorization: Bearer {{token}}
x-tenant-id: {{tenantId}}

### Register Webhooks
POST {{baseUrl}}/api/shopify/webhooks/register
Authorization: Bearer {{token}}
x-tenant-id: {{tenantId}}

### Webhook Receiver (Simulate Shopify Webhook)
POST {{baseUrl}}/api/webhook/{{tenantId}}
Content-Type: application/json

{
  "test": "webhook_event"
}
